require 'accidev.options'
require 'accidev.keymaps'
require 'accidev.plugins'

require 'accidev.bufferline'
require 'accidev.cmp'
require 'accidev.colorscheme'
require 'accidev.gitsigns'
require 'accidev.lsp'
require 'accidev.lualine'
require 'accidev.nvim-tree'
--require 'accidev.telescope'
require 'accidev.toggleterm'
require 'accidev.treesitter'
--'accidev.whichkey'
